/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nativecli;

import java.util.concurrent.Callable;

import io.micronaut.context.ApplicationContext;
import picocli.CommandLine;

@CommandLine.Command(
        name = "mycli",
        description = "Says hello",
        version = "hello 0.1.0",
        mixinStandardHelpOptions = true
)
public class App implements Callable<Integer> {

    ApplicationContext ctx;

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

    public App() {
        ctx = ApplicationContext.run();
    }
    
    @Override
    public Integer call() throws Exception { // your business logic goes here...
        System.out.println(getGreeting());
        return 0;
    }

    public String getGreeting() {
        return ctx.getBean(GithubApi.class).GET("/users/pditommaso");
    }
    
}
